newsletter/newsletter/urls.py
from django.contrib import admin
from django.urls import path
from letters.views import health_check
from .views import health_check as health_general
from letters.views import get_customer_list as get_customer_list
from letters.views import get_mailing_list as get_mailing_list
from letters.views import get_message_list as get_message_list

from letters.views import MailingCreateView, MailingDeleteView, mailing_report, MessageCreateView, MessageDeleteView, MessageUpdateView, СustomerCreateView, CustomerDeleteView, СustomerUpdateView, MessageSend
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("letters/alive", health_check),
    path("letters/all", health_check),
    path("", health_general),
    path("customer/list", get_customer_list, name='customer_list'),
    path("customer/create", СustomerCreateView.as_view(), name='create_customer'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(),
         name='customer_delete'),
    path('customer/<int:pk>', СustomerUpdateView.as_view(),
         name='customer_update'),


    
    path("mailing/list", get_mailing_list, name='mailing_list'),

    path("mailing/create", MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(),
         name='mailing_delete'),

    path("message/list", get_message_list, name='message_list'),
    path("message/create", MessageCreateView.as_view(), name='create_message'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(),
         name='message_delete'),
    path('message/<int:pk>', MessageUpdateView.as_view(),
         name='message_update'),
    path('mailing/send/<int:pk>', MessageSend, name='mailing_send'),

    path('mailing/report/', mailing_report, name='mailing_report'),
    path('users/', include('users.urls', namespace='users')),
]

newsletter/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from users.views import RegisterView, EditView, LogoutView
from users.apps import UsersConfig
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('edit/', EditView.as_view(), name='edit'),
]

newsletter/letters/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save, m2m_changed
from django.dispatch import receiver
from letters.tasks import add_mytask
from users.models import User



class Customer(models.Model):
    """Class Клиент сервиса"""
    email = models.EmailField(max_length=254, unique=True,
                              verbose_name='Контактный Email')
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=100, blank=True, null=True,
                                  verbose_name='Отчество')
    comment = models.TextField(blank=True,
                               null=True, verbose_name='Комментарий')

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.patronymic or ''}".strip()

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        permissions = [
                ("can_view_customer", "Может просматривать получателей"),
                ("can_edit_customer", "Может редактировать получателей"),
                ("can_delete_customer", "Может удалять получателей"),
            ]
# Сообщение для рассылки:
# тема письма,
# тело письма.


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'    
        permissions = [
                ("can_view_message", "Может просматривать сообщение"),
                ("can_edit_message", "Может редактировать сообщение"),
                ("can_delete_message", "Может удалять сообщение"),
            ]
# Попытка рассылки:
# дата и время последней попытки;
# статус попытки (успешно / не успешно);
# ответ почтового сервера, если он был.


class MailingAttempt(models.Model):
    STATUS_CHOICES = [
        ('successful', 'Успешно'),
        ('failed', 'Не успешно'),
    ]
    attempt_time = models.DateTimeField(default=timezone.now,
                                        verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              verbose_name='Статус попытки')
    server_response = models.TextField(blank=True, null=True,
                                       verbose_name='Ответ почтового сервера')

    def __str__(self):
        return f"Попытка рассылки {self.mailing.id} - Статус: {self.get_status_display()}"

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

# Рассылка (настройки):
# дата и время первой отправки рассылки;
# периодичность: раз в день, раз в неделю, раз в месяц;
# статус рассылки (например, завершена, создана, запущена).


class Mailing(models.Model):
    PERIODICITY_CHOICES = [
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('running', 'Запущена'),
        ('completed', 'Завершена'),
    ]

    first_send_time = models.DateTimeField(default=timezone.now,
                                           verbose_name='Дата и время первой отправки')
    periodicity = models.CharField(max_length=10, choices=PERIODICITY_CHOICES,
                                   verbose_name='Периодичность')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='created', verbose_name='Статус рассылки')

    # Связь с моделью Customer
    customers = models.ManyToManyField(Customer,
                                       related_name='mailings_cistomers',
                                       verbose_name='Клиенты')

    # Связь с моделью Message
    messages = models.ForeignKey(Message, on_delete=models.DO_NOTHING,
                                 related_name='mailings_messages',
                                 verbose_name='Сообщение')

    # Связь с моделью MailingAttempt
    attemtps = models.ManyToManyField(MailingAttempt,
                                      related_name='mailings_attempts',
                                      verbose_name='Попытки', blank=True)


    # Создатель рассылки
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mailings_created', verbose_name='Создатель', blank=True, null=True,)

    def __str__(self):
        return f"Рассылка: {self.get_periodicity_display()} - Статус: {self.get_status_display()}"

    def attempts_count(self):
        return self.attemtps.count()

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ("can_view_mailing", "Может просматривать рассылки"),
            ("can_edit_mailing", "Может редактировать рассылки"),
            ("can_delete_mailing", "Может удалять рассылки"),
        ]


# @receiver(post_save, sender=Mailing)
# def mailing_post_save(sender, instance, created, **kwargs):
#     if created or instance.status != 'created':
#         # Извлекаем список email-адресов клиентов
#         emails = instance.customers.values_list('email', flat=True)
#         add_mytask(instance, instance.periodicity, instance.first_send_time, list(emails))


@receiver(post_save, sender=Mailing)
def mailing_post_save(sender, instance, created, **kwargs):
    if created or instance.status != 'created':
        # Извлекаем список email-адресов из сообщения
        message_emails = [instance.messages.body] if instance.messages else []

        add_mytask(instance.id, instance.periodicity, [], message_emails)


@receiver(m2m_changed, sender=Mailing.customers.through)
def mailing_customers_changed(sender, instance, action, **kwargs):
    if action in ['post_add', 'post_remove', 'post_clear']:
        # Извлекаем список email-адресов клиентов
        customer_emails = list(instance.customers.values_list('email',
                                                              flat=True))

        # Извлекаем список email-адресов из сообщения
        message_emails = [instance.messages.body] if instance.messages else []

        add_mytask(instance.id, instance.periodicity, customer_emails,
                   message_emails)

newsletter/letters/forms.py
from django import forms
from letters.models import Mailing, Message, Customer


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ['creator', 'attemtps']  # Исключаем поле creator из формы


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

newsletter/letters/views.py
from django.shortcuts import render
from django.http import HttpResponse
from letters.models import Customer, Mailing, Message
from letters.forms import MailingForm, MessageForm, CustomerForm
from django.views.generic import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.contrib.auth.models import Permission
from .tasks import send_email
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from newsletter.settings import CACHE_ENABLED
from django.core.cache import cache

def health_check(request):
    return HttpResponse("service letters is alive")

# def index(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         print(f'{name} ({email})')
#     return render(request, 'letters/index.html')


def get_customer_list(request):
    customer_list = Customer.objects.all()
    context = {
        'object_list': customer_list,
        'name_list': Customer._meta.verbose_name_plural,
        'active_menu': 'clients',
    }
    return render(request, 'letters/customer_list.html', context)

@login_required  # Декоратор для проверки аутентификации пользователя
def get_mailing_list(request):
    
    # Проверяем, есть ли у пользователя право на просмотр рассылок
    
    if not request.user.has_perm('letters.can_view_mailing'):
        # запрашиваем записи с фильтром по создателю
        mailing_list = Mailing.objects.filter(creator=request.user)
        HttpResponseForbidden ('Нет прав')
    else:
        mailings = Mailing.objects.none()
        # если права есть то выдаем все записи без фильтрации
        mailing_list = Mailing.objects.all()   


    print (' права на рассылки', Permission.objects.filter(group__in=request.user.groups.all()).distinct().values_list('name', flat=True).first())

    context = {
        'object_list': mailing_list,
        'name_list': Mailing._meta.verbose_name_plural,
        'active_menu': 'mailings',
    }
    return render(request, 'letters/mailing_list.html', context)


def get_message_list(request):
    messages_list = Message.objects.all()
    context = {
        'object_list': messages_list,
        'name_list': Message._meta.verbose_name_plural,
        'active_menu': 'messages',
    }
    return render(request, 'letters/message_list.html', context)


def get_letters_list(request):
    if CACHE_ENABLED:
        # Попытка получить данные из кеша
        mailing_list = cache.get('mailing_list')
        
        if mailing_list is None:
            # Если данных нет в кеше, извлекаем их из базы данных
            mailing_list = Mailing.objects.all()
            # Сохраняем данные в кеш
            cache.set('mailing_list', mailing_list, timeout=900000)
        else: 
            mailing_list = Mailing.objects.all()
        
        context = {
                'object_list': mailing_list,
                'name_list': Mailing._meta.verbose_name_plural
            }
    return render(request, 'letters/letters_list.html', context)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing_list')

    def form_valid(self, form):
        # Устанавливаем текущего пользователя как создателя рассылки
        form.instance.creator = self.request.user
        return super().form_valid(form)

class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('message_list')


class СustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('customer_list')


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = 'letters/mailing_delete.html'
    success_url = reverse_lazy('mailing_list')


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'letters/customer_delete.html'
    success_url = reverse_lazy('customer_list')



class MessageDeleteView(DeleteView):
    model = Message
    template_name = 'letters/message_delete.html'
    success_url = reverse_lazy('message_list')


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'letters/message_edit.html'  # Укажите ваш шаблон
    success_url = reverse_lazy('message_list')  # URL для перенаправления после успешного редактирования


class СustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'letters/customer_edit.html'  # Укажите ваш шаблон
    success_url = reverse_lazy('customer_list')  # URL для перенаправления после успешного редактирования


@login_required  # Декоратор для проверки аутентификации пользователя
def mailing_report(request):
    mailings = Mailing.objects.prefetch_related('customers', 'attemtps').filter(creator=request.user)
    context = {
        'mailings': mailings,
        'active_menu': 'orders',
    }
    return render(request, 'letters/mailing_report.html', context)

def MessageSend(request, pk):
    current_mailing = get_object_or_404(Mailing.objects.prefetch_related('customers', 'messages'), id=pk)
    # Извлекаем email клиентов
    customer_emails = [customer.email for customer in current_mailing.customers.all()]
    # Извлекаем тело сообщения
    message_body = current_mailing.messages.body if current_mailing.messages else None
    message_subject = current_mailing.messages.subject if current_mailing.messages else None

    # Рассылаем 
    for m in customer_emails:
        send_email(m, message_body, pk, message_subject)
    return redirect('mailing_list')

newsletter/letters/templates/letters/base.html
{% load static %}
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Сервис рассылок</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/dashboard/dashboard.css" rel="stylesheet">
  <style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style></head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Сервис рассылок</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>
<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            {% if user.is_authenticated %}
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link {% if active_menu == 'clients' %} active {% endif %}" href="{% url 'customer_list' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Клиенты
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_menu == 'messages' %} active {% endif %} " href="{% url 'message_list' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                  Шаблоны сообщений
                </a>
              </li>              
              <li class="nav-item">
                <a class="nav-link {% if active_menu == 'mailings' %} active {% endif %} " href="{% url 'mailing_list' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Рассылки
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_menu == 'orders' %} active {% endif %}" href="{% url 'mailing_report' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Reports
                </a>
              </li>
              
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Пользователь</span>
                <a class="link-secondary" href="#" aria-label="Add a new report">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
                </a>
              </h6>
            </ul>
            {% endif %}
            <ul class="nav flex-column mb-2">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#" id="logout-link">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Выход
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:edit' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Редактировать
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Вход
                </a>
              </li>              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Регистрация
                </a>
              </li>

              {% endif %}
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

        {% block content %}
        {% endblock %}

        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
    <script>
      document.getElementById('logout-link').addEventListener('click', function(event) {
          event.preventDefault(); // Отменяем стандартное поведение ссылки
          const form = document.createElement('form');
          form.method = 'POST';
          form.action = "{% url 'users:logout' %}"; // Укажите URL для выхода
          const csrfToken = '{{ csrf_token }}'; // Получите CSRF токен
          const hiddenInput = document.createElement('input');
          hiddenInput.type = 'hidden';
          hiddenInput.name = 'csrfmiddlewaretoken';
          hiddenInput.value = csrfToken;
          form.appendChild(hiddenInput);
          document.body.appendChild(form);
          form.submit(); // Отправляем форму
      });
      </script>
      
  
  </body>
</html>

newsletter/letters/templates/letters/customer_delete.html
{% extends 'letters/base.html' %}
        {% block content %}
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="col-6">
                <div class="card">



                  <div class="card-header">
                    <h2 class="card-title">Удаление получателя сообщений</h2>
                  </div>
                  <div class="card-body">
                    <form method="post">
                      {% csrf_token %}
                      <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
                      <button type="submit">Удалить</button>
                  </form>
                  
                  </div>
                  <div class="card-footer"></div>




                </div>
              </div>
              </div>
            </div>



            {% endblock %}

newsletter/letters/templates/letters/customer_edit.html
{% extends 'letters/base.html' %}
        {% block content %}


          <div class="album py-5 bg-light">
            <div class="container">
              <div class="col-6">
                <div class="card">



                  <div class="card-header">
                    <h2 class="card-title">Изменение получателя сообщений</h2>
                  </div>
                  <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                  
                  </div>
                  <div class="card-footer"></div>




                </div>
              </div>
              </div>
            </div>



            {% endblock %}

newsletter/letters/templates/letters/customer_form.html
{% extends 'letters/base.html' %}
  {% block content %}

      <div class="album py-5 bg-light">
            <div class="container">
              <div class="col-6">
                <div class="card">
                  <div class="card-header">
                    <h2 class="card-title">Добавление нового получателя сообщений</h2>
                  </div>
                  <div class="card-body">
                    <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                  </div>
                  <div class="card-footer"></div>
                </div>
              </div>
              </div>
            </div>
  {% endblock %}

newsletter/letters/templates/letters/customer_list.html
{% extends 'letters/base.html' %}
        {% block content %}
        {% if user.is_authenticated %}
          <div class="row">
          <h2>{{ name_list }}</h2>
            <div class="album py-5 bg-light">
              <div class="container">
          
                <div class="row">
                  {% for object in object_list %}
                  <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                      <div class="card-body">
                        <p class="card-text">{{ object|title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="btn-group">
                            <a href="{% url 'customer_update' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                            <a href="{% url 'customer_delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}

                </div>
              </div>
            </div>
          </div>

          <div >
            <a href="{% url 'create_customer' %}" class="btn btn-primary btn-lg">Добавить нового получателя сообщений</a>
          </div>
          <h2>Статистика</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>№</th>
                  <th>Количество записей</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>{{ object_list.count }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          {% else %}
          <p>Пожалуйста, войдите в систему для доступа к этой функции.</p>
          {% endif %}

          {% endblock %}

newsletter/letters/templates/letters/mailing_delete.html
{% extends 'letters/base.html' %}
        {% block content %}
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="col-6">
                <div class="card">



                  <div class="card-header">
                    <h2 class="card-title">Удаление рассылки</h2>
                  </div>
                  <div class="card-body">
                    <form method="post">
                      {% csrf_token %}
                      <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
                      <button type="submit">Удалить</button>
                  </form>
                  
                  </div>
                  <div class="card-footer"></div>




                </div>
              </div>
              </div>
            </div>



            {% endblock %}